# Generated by Django 6.0 on 2025-12-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AVInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avid', models.CharField(max_length=50, unique=True, verbose_name='AV编号')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('source', models.CharField(max_length=100, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AV信息',
                'verbose_name_plural': 'AV信息',
                'db_table': 'av_info',
                'ordering': ['-created_at'],
            },
        ),
    ]
