# Generated by Django 6.0 on 2025-12-31 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nassav', '0002_avresource'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='avresource',
            new_name='nassav_avre_avid_fcdb07_idx',
            old_name='nassav_avre_avid_idx',
        ),
        migrations.RenameIndex(
            model_name='avresource',
            new_name='nassav_avre_title_d0556f_idx',
            old_name='nassav_avre_title_idx',
        ),
        migrations.RenameIndex(
            model_name='avresource',
            new_name='nassav_avre_source_bd38fa_idx',
            old_name='nassav_avre_source_idx',
        ),
        migrations.AlterField(
            model_name='avresource',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
