# Generated by assistant: add indexes to improve actor filtering and aggregation
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "nassav",
            "0003_rename_nassav_avre_avid_idx_nassav_avre_avid_fcdb07_idx_and_more",
        ),
    ]

    operations = [
        # Add index on metadata_saved_at for faster ordering/filtering by time
        migrations.AddIndex(
            model_name="avresource",
            index=models.Index(
                fields=["metadata_saved_at"], name="nassav_avre_metadata_saved_at_idx"
            ),
        ),
        # Create index on the many-to-many through table for actor lookups
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS nassav_avresource_actors_actor_id_idx "
                "ON nassav_avresource_actors (actor_id);"
            ),
            reverse_sql=("DROP INDEX IF EXISTS nassav_avresource_actors_actor_id_idx;"),
        ),
    ]
