# Generated by Django 6.0 on 2026-01-01 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nassav", "0004_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="avresource",
            name="nassav_avre_metadata_saved_at_idx",
        ),
    ]
