# Generated by Django 6.0 on 2026-01-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nassav', '0005_remove_avresource_nassav_avre_metadata_saved_at_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='avresource',
            name='source_title',
            field=models.CharField(blank=True, help_text='Source 获取的标题（备用，来自 MissAV/Jable 等）', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='avresource',
            name='translated_title',
            field=models.CharField(blank=True, help_text='翻译后的标题（中文，由 Ollama 翻译）', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='avresource',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text='Scraper 获取的标题（通常为日语，来自 Javbus）', max_length=512),
        ),
    ]
