# Generated by Django 6.0 on 2026-01-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nassav", "0006_add_title_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="avresource",
            name="translation_status",
            field=models.CharField(
                choices=[
                    ("pending", "待翻译"),
                    ("translating", "翻译中"),
                    ("completed", "已完成"),
                    ("failed", "翻译失败"),
                    ("skipped", "跳过"),
                ],
                db_index=True,
                default="pending",
                help_text="翻译状态",
                max_length=20,
            ),
        ),
    ]
