# Generated by Django 6.0 on 2026-01-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nassav", "0007_add_translation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="avatar_url",
            field=models.URLField(blank=True, null=True, help_text="Javbus 头像 URL"),
        ),
        migrations.AddField(
            model_name="actor",
            name="avatar_filename",
            field=models.CharField(
                max_length=255,
                blank=True,
                null=True,
                help_text="头像文件名（存储在 resource/avatar/）",
            ),
        ),
        migrations.AddField(
            model_name="actor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="最后更新时间"),
        ),
    ]
