# Generated by Django 6.0 on 2026-01-03 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nassav", "0008_add_actor_avatar_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avresource",
            old_name="title",
            new_name="original_title",
        ),
    ]
