# Generated by Django 6.0 on 2026-01-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nassav", "0009_rename_title_to_original_title"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="avresource",
            name="nassav_avre_title_d0556f_idx",
        ),
        migrations.AddField(
            model_name="avresource",
            name="is_favorite",
            field=models.BooleanField(db_index=True, default=False, help_text="是否收藏"),
        ),
        migrations.AddField(
            model_name="avresource",
            name="watched",
            field=models.BooleanField(db_index=True, default=False, help_text="是否已观看"),
        ),
        migrations.AlterField(
            model_name="avresource",
            name="original_title",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Scraper 获取的原始标题（通常为日语，来自 Javbus）",
                max_length=512,
            ),
        ),
        migrations.AddIndex(
            model_name="avresource",
            index=models.Index(
                fields=["original_title"], name="nassav_avre_origina_ac26b6_idx"
            ),
        ),
    ]
