# Generated by Django 6.0 on 2026-03-29 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nassav", "0011_rename_and_add_metadata_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommender_id", models.CharField(db_index=True, max_length=64)),
                ("strategy_id", models.CharField(db_index=True, max_length=64)),
                ("request_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("request_payload", models.JSONField(default=dict)),
                ("seed_summary", models.JSONField(default=list)),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("random_seed", models.BigIntegerField(default=0)),
                (
                    "generated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "nassav_recommendation_snapshot",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="recommendationsnapshot",
            index=models.Index(
                fields=["recommender_id", "strategy_id", "request_fingerprint"],
                name="nassav_recsnap_lkp_idx",
            ),
        ),
        migrations.CreateModel(
            name="RecommendationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("avid", models.CharField(db_index=True, max_length=50)),
                ("title", models.CharField(blank=True, max_length=512)),
                ("detail_url", models.URLField(blank=True, max_length=1024)),
                ("cover_url", models.URLField(blank=True, max_length=1024)),
                ("source", models.CharField(blank=True, db_index=True, max_length=128)),
                ("score", models.FloatField(default=0.0)),
                ("search_rank", models.IntegerField(blank=True, null=True)),
                ("reasons", models.JSONField(default=list)),
                ("matched_seeds", models.JSONField(default=list)),
                ("score_breakdown", models.JSONField(default=list)),
                ("raw_metrics", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="nassav.recommendationsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "nassav_recommendation_item",
                "ordering": ["snapshot_id", "rank"],
            },
        ),
        migrations.AddIndex(
            model_name="recommendationitem",
            index=models.Index(
                fields=["snapshot", "avid"], name="nassav_recitem_sa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "rank"), name="nassav_recitem_sr_uniq"
            ),
        ),
    ]
