# Generated by Django 6.0 on 2026-03-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nassav", "0012_recommendationitem_recommendationsnapshot_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="avresource",
            name="nassav_avre_avid_fcdb07_idx",
        ),
        migrations.RemoveIndex(
            model_name="avresource",
            name="nassav_avre_source_bd38fa_idx",
        ),
        migrations.RemoveIndex(
            model_name="avresource",
            name="nassav_avre_origina_ac26b6_idx",
        ),
        migrations.AlterField(
            model_name="avresource",
            name="metadata_updated_at",
            field=models.DateTimeField(auto_now=True, help_text="元数据最后更新时间"),
        ),
    ]
