# Generated by Django 6.0 on 2026-03-29 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nassav", "0013_remove_avresource_nassav_avre_avid_fcdb07_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avid", models.CharField(db_index=True, max_length=50)),
                (
                    "feedback",
                    models.CharField(
                        choices=[("like", "喜欢"), ("dislike", "不喜欢")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("feedback_value", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="nassav.recommendationitem",
                    ),
                ),
            ],
            options={
                "db_table": "nassav_recommendation_feedback",
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["avid", "feedback"], name="nassav_recfb_af_idx"
                    )
                ],
            },
        ),
    ]
