# Generated by Django 6.0 on 2026-03-29 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nassav", "0014_recommendationfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActorSourceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(db_index=True, max_length=32)),
                ("source_actor_name", models.CharField(blank=True, max_length=255)),
                (
                    "source_actor_slug",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_actor_url",
                    models.URLField(blank=True, max_length=1024),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("match_method", models.CharField(default="manual", max_length=32)),
                ("confidence", models.FloatField(default=1.0)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_mappings",
                        to="nassav.actor",
                    ),
                ),
            ],
            options={
                "db_table": "nassav_actor_source_mapping",
                "ordering": ["source_name", "actor_id"],
                "indexes": [
                    models.Index(
                        fields=["source_name", "source_actor_name"],
                        name="nassav_actsrc_source_name_idx",
                    ),
                    models.Index(
                        fields=["source_name", "is_active"],
                        name="nas_actsrc_src_active_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("actor", "source_name"),
                        name="nas_actsrc_actor_src_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("source_name", "source_actor_slug"),
                        name="nassav_actsrc_source_slug_uniq",
                    ),
                ],
            },
        ),
    ]
