# Generated by Django 6.0 on 2026-03-30 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nassav", "0016_genresourcesourcemapping"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="genresourcemapping",
            name="nassav_gensrc_source_slug_uniq",
        ),
    ]
