# Generated by Django 6.0 on 2026-04-03 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
import re


def _normalize_value(value):
    return re.sub(r"\s+", " ", str(value or "").strip()).casefold()


def _source_identifier(seed_type, payload):
    payload = dict(payload or {})
    if seed_type == "actor":
        return str(payload.get("model_slug", "")).strip().lower()
    if seed_type == "genre":
        return str(payload.get("genre_slug", "")).strip().lower()
    return ""


def forward_fill_recommendation_structures(apps, schema_editor):
    RecommendationAvidBlocklist = apps.get_model(
        "nassav", "RecommendationAvidBlocklist"
    )
    RecommendationFeedback = apps.get_model("nassav", "RecommendationFeedback")
    RecommendationItem = apps.get_model("nassav", "RecommendationItem")
    RecommendationItemSeed = apps.get_model("nassav", "RecommendationItemSeed")
    RecommendationSeedProfile = apps.get_model("nassav", "RecommendationSeedProfile")

    profile_map = {}
    for item in RecommendationItem.objects.all().iterator():
        for seed in item.matched_seeds or []:
            seed_type = str(seed.get("seed_type", "")).strip().lower()
            seed_value = str(seed.get("value", "")).strip()
            if not seed_type or not seed_value:
                continue
            normalized_value = _normalize_value(seed_value)
            lookup_payload = dict(seed.get("lookup_payload") or {})
            source_name = str(lookup_payload.get("source_name", "")).strip().lower()
            source_identifier = _source_identifier(seed_type, lookup_payload)
            RecommendationItemSeed.objects.get_or_create(
                item_id=item.pk,
                seed_key=f"{seed_type}:{seed_value}",
                defaults={
                    "seed_type": seed_type,
                    "seed_value": seed_value,
                    "normalized_value": normalized_value,
                    "source": str(seed.get("source", "")).strip(),
                    "source_name": source_name,
                    "source_identifier": source_identifier,
                    "aliases": list(seed.get("aliases") or []),
                    "weight": float(seed.get("weight") or 0.0),
                    "resource_count": max(int(seed.get("resource_count") or 0), 0),
                    "preference_score": float(seed.get("preference_score") or 0.0),
                    "created_at": getattr(item, "created_at", None)
                    or django.utils.timezone.now(),
                },
            )
            identity = (
                seed_type,
                normalized_value,
                source_name,
                source_identifier,
            )
            payload = profile_map.setdefault(
                identity,
                {
                    "seed_type": seed_type,
                    "value": seed_value,
                    "aliases": [],
                    "recommended_count": 0,
                    "disliked_count": 0,
                    "last_recommended_at": None,
                },
            )
            payload["recommended_count"] += 1
            payload["aliases"] = _merge_aliases(
                payload["aliases"],
                list(seed.get("aliases") or []),
            )
            if item.snapshot_id:
                generated_at = getattr(
                    getattr(item, "snapshot", None), "generated_at", None
                )
                if generated_at and (
                    payload["last_recommended_at"] is None
                    or generated_at > payload["last_recommended_at"]
                ):
                    payload["last_recommended_at"] = generated_at

    for feedback in RecommendationFeedback.objects.filter(
        feedback="dislike"
    ).iterator():
        avid = str(feedback.avid or "").strip().upper()
        if avid:
            RecommendationAvidBlocklist.objects.get_or_create(
                avid=avid,
                defaults={
                    "source": "legacy_feedback",
                    "reason": "dislike",
                    "created_at": getattr(feedback, "created_at", None)
                    or django.utils.timezone.now(),
                    "updated_at": getattr(feedback, "updated_at", None)
                    or django.utils.timezone.now(),
                },
            )
        item = getattr(feedback, "item", None)
        if item is None:
            continue
        for seed in item.matched_seeds or []:
            seed_type = str(seed.get("seed_type", "")).strip().lower()
            seed_value = str(seed.get("value", "")).strip()
            if not seed_type or not seed_value:
                continue
            lookup_payload = dict(seed.get("lookup_payload") or {})
            identity = (
                seed_type,
                _normalize_value(seed_value),
                str(lookup_payload.get("source_name", "")).strip().lower(),
                _source_identifier(seed_type, lookup_payload),
            )
            payload = profile_map.setdefault(
                identity,
                {
                    "seed_type": seed_type,
                    "value": seed_value,
                    "aliases": list(seed.get("aliases") or []),
                    "recommended_count": 0,
                    "disliked_count": 0,
                    "last_recommended_at": None,
                },
            )
            payload["disliked_count"] += 1

    for identity, payload in profile_map.items():
        RecommendationSeedProfile.objects.update_or_create(
            seed_type=identity[0],
            normalized_value=identity[1],
            source_name=identity[2],
            source_identifier=identity[3],
            defaults={
                "value": payload["value"],
                "aliases": payload["aliases"],
                "recommended_count": payload["recommended_count"],
                "disliked_count": payload["disliked_count"],
                "last_recommended_at": payload["last_recommended_at"],
            },
        )


def reverse_fill_recommendation_structures(apps, schema_editor):
    RecommendationAvidBlocklist = apps.get_model(
        "nassav", "RecommendationAvidBlocklist"
    )
    RecommendationItemSeed = apps.get_model("nassav", "RecommendationItemSeed")
    RecommendationSeedProfile = apps.get_model("nassav", "RecommendationSeedProfile")
    RecommendationAvidBlocklist.objects.all().delete()
    RecommendationItemSeed.objects.all().delete()
    RecommendationSeedProfile.objects.all().delete()


def _merge_aliases(base, extra):
    merged = []
    seen = set()
    for value in [*(base or []), *(extra or [])]:
        normalized = str(value or "").strip()
        if not normalized:
            continue
        token = normalized.casefold()
        if token in seen:
            continue
        seen.add(token)
        merged.append(normalized)
    return merged


class Migration(migrations.Migration):
    dependencies = [
        (
            "nassav",
            "0017_remove_genresourcesourcemapping_nassav_gensrc_source_slug_uniq",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationAvidBlocklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avid", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "source",
                    models.CharField(
                        db_index=True, default="user_feedback", max_length=32
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nassav_recommendation_avid_blocklist",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationSeedProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seed_type",
                    models.CharField(
                        choices=[("actor", "演员"), ("genre", "类别")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("normalized_value", models.CharField(db_index=True, max_length=255)),
                (
                    "source_name",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "source_identifier",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("is_blocked", models.BooleanField(db_index=True, default=False)),
                ("block_reason", models.CharField(blank=True, max_length=255)),
                ("recommended_count", models.PositiveIntegerField(default=0)),
                ("accepted_count", models.PositiveIntegerField(default=0)),
                ("disliked_count", models.PositiveIntegerField(default=0)),
                ("last_recommended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nassav_recommendation_seed_profile",
                "ordering": [
                    "seed_type",
                    "normalized_value",
                    "source_name",
                    "source_identifier",
                ],
                "indexes": [
                    models.Index(
                        fields=["seed_type", "is_blocked"],
                        name="nas_recseedprofile_type_block_idx",
                    ),
                    models.Index(
                        fields=["source_name", "source_identifier"],
                        name="nas_recseedprofile_src_ident_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "seed_type",
                            "normalized_value",
                            "source_name",
                            "source_identifier",
                        ),
                        name="nassav_recseedprofile_identity_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecommendationItemSeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed_type", models.CharField(db_index=True, max_length=16)),
                ("seed_value", models.CharField(max_length=255)),
                ("normalized_value", models.CharField(db_index=True, max_length=255)),
                ("seed_key", models.CharField(db_index=True, max_length=320)),
                ("source", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "source_name",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "source_identifier",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("weight", models.FloatField(default=0.0)),
                ("resource_count", models.PositiveIntegerField(default=0)),
                ("preference_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_seeds",
                        to="nassav.recommendationitem",
                    ),
                ),
            ],
            options={
                "db_table": "nassav_recommendation_item_seed",
                "ordering": ["item_id", "id"],
                "indexes": [
                    models.Index(
                        fields=["seed_type", "normalized_value"],
                        name="nas_recseed_type_norm_idx",
                    ),
                    models.Index(
                        fields=["source_name", "source_identifier"],
                        name="nas_recseed_src_ident_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "seed_key"),
                        name="nassav_recitemseed_item_key_uniq",
                    )
                ],
            },
        ),
        migrations.RunPython(
            forward_fill_recommendation_structures,
            reverse_fill_recommendation_structures,
        ),
    ]
